#1 [internal] load .dockerignore
#1 transferring context: 2B done
#1 DONE 2.0s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 32B done
#2 DONE 3.2s

#3 [internal] load metadata for docker.io/library/python:3.8
#3 DONE 2.7s

#4 [1/6] FROM docker.io/library/python:3.8@sha256:2e652376e0db17d97355ebfe7871736fb30d551ab164172157f7982ccb73c5d9
#4 DONE 0.0s

#5 [internal] load build context
#5 transferring context:
#5 transferring context: 50.78kB 0.0s done
#5 DONE 0.9s

#6 [2/6] WORKDIR /app
#6 CACHED

#7 [3/6] COPY requirements.txt .
#7 CACHED

#8 [4/6] RUN pip config set global.index-url https://pypi.org/simple
#8 CACHED

#9 [5/6] RUN pip3 install -r requirements.txt
#9 4.108 WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f6ceff0c7c0>: Failed to establish a new connection: [Errno 111] Connection refused'))': /simple/markupsafe/
#9 4.610 WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f6ceff0c460>: Failed to establish a new connection: [Errno 111] Connection refused'))': /simple/markupsafe/
#9 5.613 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f6ceff1b2b0>: Failed to establish a new connection: [Errno 111] Connection refused'))': /simple/markupsafe/
#9 7.616 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f6ceff1b250>: Failed to establish a new connection: [Errno 111] Connection refused'))': /simple/markupsafe/
#9 11.62 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f6ceff1b880>: Failed to establish a new connection: [Errno 111] Connection refused'))': /simple/markupsafe/
#9 11.63 ERROR: Could not find a version that satisfies the requirement MarkupSafe (from versions: none)
#9 11.63 ERROR: No matching distribution found for MarkupSafe
#9 ERROR: executor failed running [/bin/sh -c pip3 install -r requirements.txt]: exit code: 1
------
 > [5/6] RUN pip3 install -r requirements.txt:
#9 4.108 WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f6ceff0c7c0>: Failed to establish a new connection: [Errno 111] Connection refused'))': /simple/markupsafe/
#9 4.610 WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f6ceff0c460>: Failed to establish a new connection: [Errno 111] Connection refused'))': /simple/markupsafe/
#9 5.613 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f6ceff1b2b0>: Failed to establish a new connection: [Errno 111] Connection refused'))': /simple/markupsafe/
#9 7.616 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f6ceff1b250>: Failed to establish a new connection: [Errno 111] Connection refused'))': /simple/markupsafe/
#9 11.62 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f6ceff1b880>: Failed to establish a new connection: [Errno 111] Connection refused'))': /simple/markupsafe/
#9 11.63 ERROR: Could not find a version that satisfies the requirement MarkupSafe (from versions: none)
#9 11.63 ERROR: No matching distribution found for MarkupSafe
------
ERROR: failed to solve: executor failed running [/bin/sh -c pip3 install -r requirements.txt]: exit code: 1
